name: Install Dependencies with Bun

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Tools & Dependencies
        uses: ./.github/actions/install

      - name: Build web preview
        run: pnpm build
        working-directory: ./app

      # - name: Install dependencies using Bun
      #   run: bun install
      #   working-directory: ./bot

      # - name: Run
      #   run: bun run index.ts
      #   working-directory: ./bot
